answers:
  outputs:
    dev:
      dataset: dbt_ozgur
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: stunning-object-386721
      threads: 60
      type: bigquery
  target: dev
